modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"

[[mods]]
modId="construction_essentials"
version="0.0.1"
displayName="Construction Essentials"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://drakenxi.net"
authors="Draken"

[[dependencies.construction_essentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




